### ISSUE TITLE
npm install / yarn install instructions missing

### ISSUE THREAD

**Issue by bjohnso5** [JesseObrien/signalr-jwt#1]
The setup instructions don't mention running an `npm i` / `yarn` in the `wwwroot` folder, project no worky without the signalr js files.

**Comment by jesseobrien** [comment]
Too true! Will fix 🥂

**Comment by jesseobrien** [comment]
Fixed via 17eb99bf007bd43294ebe93aa15c8eeede10d469.

Thanks!
